[package]
name = "tui_calculater"
version = "0.1.0"
authors = ["drumgiovanni <giovannithedev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.7.0"
termion = "1.5.4"
